updated terraform.yaml

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -336,17 +336,17 @@ jobs:
           #fi
 
           # outputs lots of 'my.resource: Refreshing state...' which pollutes the plan posted to the PR
-          #terraform plan -input=false -no-color
+          terraform plan -input=false -no-color
           #
-          # workaround
+          # attempted workaround, but loses errors posting nothing to PR when it fails, and even accepting, the show step fails because the tfplan wasn't generated
           #
           # even if the plan fails, still try to show the plan
-          exit_code=0
-          if ! terraform plan -input=false -no-color >/dev/null -out=tfplan; then
-            exit_code=1
-          fi
-          terraform show tfplan
-          exit "$exit_code"
+          #exit_code=0
+          #if ! terraform plan -input=false -no-color >/dev/null -out=tfplan; then
+          #  exit_code=1
+          #fi
+          #terraform show tfplan
+          #exit "$exit_code"
 
       - uses: actions/github-script@0.9.0
         if: github.event_name == 'pull_request'
