updated trivy_image.yaml

diff --git a/.github/workflows/trivy_image.yaml b/.github/workflows/trivy_image.yaml
--- a/.github/workflows/trivy_image.yaml
+++ b/.github/workflows/trivy_image.yaml
@@ -67,14 +67,40 @@ env:
 
 jobs:
   trivy:
-    name: Trivy GitHub Security Alerts
+    name: Trivy Image
     runs-on: ubuntu-latest
-    #container: aquasec/trivy:latest
+    container: aquasec/trivy:latest
     steps:
       - name: Environment
         run: env | sort
 
-      - uses: actions/checkout@v3
+      - name: Trivy Image
+        run: |
+          # informational to see all issues
+          trivy image --no-progress "$IMAGE"
+
+  trivy_severity:
+    name: Trivy Image severity
+    runs-on: ubuntu-latest
+    container: aquasec/trivy:latest
+    steps:
+      - name: Environment
+        run: env | sort
+
+      - name: Trivy Image severity exit 1
+        if: ${{ inputs.severity || github.event.inputs.severity }}
+        env:
+          SEVERITY: ${{ inputs.severity || github.event.inputs.severity }}
+        run: |
+          # fail the pipeline if any of the issues are in $SEVERITY eg. HIGH,CRITICAL
+          trivy image --no-progress --exit-code 1 --severity "$SEVERITY" "$IMAGE"
+
+  trivy_github:
+    name: Trivy Image GitHub Security tab
+    runs-on: ubuntu-latest
+    steps:
+      - name: Environment
+        run: env | sort
 
       - name: Run Trivy vulnerability scanner to generate sarif
         #if: ${{ ! ( inputs.no_sarif || github.event.inputs.sarif ) }}
